### ISSUE TITLE
ValueError: Cannot embed the 'svg' image format

### ISSUE THREAD

**Issue by QieSima** [ialhashim/DenseDepth#118]
As title said, I got such kind of error when I run this project in anaconda environment with nyu data, how can I deal with this?

**Comment by QieSima** [comment]
`Model created.
Output: ./models/1588092248-n6336-e20-bs8-lr0.0001-densedepth_nyu
Traceback (most recent call last):
  File "train.py", line 60, in <module>
    plot_model(model, to_file=runPath+'/model_plot.svg', show_shapes=True, show_layer_names=True)
  File "/home1/simaqie/DenseDepth/anaconda3/lib/python3.7/site-packages/keras/utils/vis_utils.py", line 251, in plot_model
    return display.Image(filename=to_file)
  File "/home1/simaqie/DenseDepth/anaconda3/lib/python3.7/site-packages/IPython/core/display.py", line 1195, in __init__
    raise ValueError("Cannot embed the '%s' image format" % (self.format))
ValueError: Cannot embed the 'svg' image format`

**Comment by ialhashim** [comment]
You can comment out the visualization line.
