### ISSUE TITLE
Shape issues when using Keras

### ISSUE THREAD

**Issue by ahmeda14960** [ialhashim/DenseDepth#128]
Hello all,

I am trying to use the dense depth network that was trained on the KITTI dataset for inference on a single image. After looking through test.py, I put together the following script
```
from keras.models import Model, load_model
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt
import keras.backend as K
import tensorflow as tf
from keras.engine.topology import Layer, InputSpec
import keras.utils.conv_utils as conv_utils

existing = 'kitti.h5'
custom_objects = {'BilinearUpSampling2D': BilinearUpSampling2D, 'depth_loss_function': None}
model = load_model(existing, custom_objects=custom_objects, compile=False)

# just test on one image
# convert this image to an RGB numpy array
image_files = ['28.png']
data = load_images(image_files)


pred_arr = predict(model, data, 1e-3, 80)

plt.imshow(pred_arr, cmap='magma_r', vmin=0, vmax=80)
plt.show()
```

However, after running this seemingly innocent script I got the following error:
```bash
Traceback (most recent call last):
  File "main.py", line 100, in <module>
    pred_arr = predict(model, data, 1e-3, 80)
  File "main.py", line 86, in predict
    predictions = model.predict(images, batch_size=batch_size)
  File "C:\Users\skull\AppData\Roaming\Python\Python37\site-packages\keras\engine\training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "C:\Users\skull\AppData\Roaming\Python\Python37\site-packages\keras\engine\training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "C:\Users\skull\AppData\Roaming\Python\Python37\site-packages\keras\engine\training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected input_1 to have shape (None, None, 3) but got array with shape (320, 1024, 4)
```

Do you all know why this might be happening? My script above is essentially the same as the test.py file in this repository, so I'm not sure why I'm getting shape issues.

**Comment by ialhashim** [comment]
The image needs to be 3 channels, it seems you are inputting a 4 channel image.

**Comment by ahmeda14960** [comment]
Do you have any guesses as to why the image is being read as 4-channels? It's a simple PNG file. Should I have it in another format such as JPEG?
