### ISSUE TITLE
Tensorflow 2.2 AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images'

### ISSUE THREAD

**Issue by ahojukka5** [ialhashim/DenseDepth#133]
When running `test.py`, I get the error message given above. I guess they have been changed the name of the function to `resize`?

Full traceback:

```text
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model = load_model(args.model, custom_objects=custom_objects, compile=False)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in load_wrapper
    return load_function(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 584, in load_model
    model = _deserialize_model(h5dict, custom_objects, compile)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 274, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/saving.py", line 627, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 1075, in from_config
    process_node(layer, node_data)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/network.py", line 1025, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/keras/engine/base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/jukka/dev/DenseDepth/layers.py", line 38, in call
    return tf.image.resize_images(inputs, [height, width], method=tf.image.ResizeMethod.BILINEAR, align_corners=True)
AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images'
```

I also had to remove `align_corners = True`.

**Comment by ialhashim** [comment]
Yes, its a versioning issue I believe.
