### ISSUE TITLE
 AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images'

### ISSUE THREAD

**Issue by Fennecai** [ialhashim/DenseDepth#138]
```
(base) H:\Antonios stuff\devstuff\python\AI\DenseDepth-master>python test.py --input "H:\Antonios stuff\devstuff\python\AI\DenseDepth-master\examples\1_image.png"
Using TensorFlow backend.
Loading model...
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    model = load_model(args.model, custom_objects=custom_objects, compile=False)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 373, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 987, in from_config
    config, custom_objects)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 2029, in reconstruct_from_config
    process_node(layer, node_data)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\network.py", line 1977, in process_node
    output_tensors = layer(input_tensors, **kwargs)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 922, in __call__
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "C:\Users\aekna\Anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 265, in wrapper
    raise e.ag_error_metadata.to_exception(e)
AttributeError: in user code:

    H:\Antonios stuff\devstuff\python\AI\DenseDepth-master\layers.py:38 call  *
        return tf.image.resize_images(inputs, [height, width], method=tf.image.ResizeMethod.BILINEAR, align_corners=True)

    AttributeError: module 'tensorflow._api.v2.image' has no attribute 'resize_images'
```

maybe I'm using this wrong....? i am still learning how to run projects like these

**Comment by thima2017** [comment]
I found the solution there https://better-coding.com/solved-tensorflow-attributeerror-module-tensorflow-_api-v2-image-has-no-attribute-resize_images/

**Comment by thima2017** [comment]
I just deleted align_corners and seems it works. The final view of that string:
```
return tf.image.resize(inputs, [height, width], method=tf.image.ResizeMethod.BILINEAR)
```
