### ISSUE TITLE
GL errors demo.py

### ISSUE THREAD

**Issue by mosvlad** [ialhashim/DenseDepth#143]
Some errors while running demo.py
App runs, but 3D view window is black.

```
Traceback (most recent call last):
  File "demo.py", line 301, in initializeGL
    GL.glShadeModel(GL.GL_FLAT)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xed\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xee\xef\xe5\xf0\xe0\xf6\xe8\xff',
        baseOperation = glShadeModel,
        cArguments = (GL_FLAT,)
)
Traceback (most recent call last):
  File "demo.py", line 274, in resizeGL
    GL.glViewport(0, 0, width, height)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xed\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xee\xef\xe5\xf0\xe0\xf6\xe8\xff',
        baseOperation = glViewport,
        cArguments = (0, 0, 640, 744)
)
Traceback (most recent call last):
  File "demo.py", line 326, in paintGL
    GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\platform\baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xed\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xee\xef\xe5\xf0\xe0\xf6\xe8\xff',
        baseOperation = glClear,
        cArguments = (16640,)
)
Traceback (most recent call last):
  File "demo.py", line 326, in paintGL
    GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xed\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xee\xef\xe5\xf0\xe0\xf6\xe8\xff',
        baseOperation = glClear,
        cArguments = (16640,)
)
Traceback (most recent call last):
  File "demo.py", line 326, in paintGL
    GL.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\pyopengl-3.1.5-py3.6.egg\OpenGL\error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'\xed\xe5\xe4\xee\xef\xf3\xf1\xf2\xe8\xec\xe0\xff \xee\xef\xe5\xf0\xe0\xf6\xe8\xff',
        baseOperation = glClear,
        cArguments = (16640,)
)
```

**Comment by ialhashim** [comment]
I have never faced such an issue before. I think it has to do with the python openly library so you might get more relevant answers asking there.
