### ISSUE TITLE
Model Predict

### ISSUE THREAD

**Issue by jonasjohansson** [ialhashim/DenseDepth#171]
Running Tensorflow 2.4.1 and demo.py with a new image selected and clicking load model - receiving this error: 

_ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.
Traceback (most recent call last):_

Any pointers?

**Comment by jonasjohansson** [comment]
2021-02-10 11:09:18.327060: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-10 11:09:18.327413: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-02-10 11:09:18.328270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce RTX 3090 computeCapability: 8.6
coreClock: 1.695GHz coreCount: 82 deviceMemorySize: 24.00GiB deviceMemoryBandwidth: 871.81GiB/s
2021-02-10 11:09:18.328382: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-02-10 11:09:18.328456: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-02-10 11:09:18.328522: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-02-10 11:09:18.328589: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-02-10 11:09:18.328653: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-02-10 11:09:18.328716: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-02-10 11:09:18.328778: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-02-10 11:09:18.328839: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-02-10 11:09:18.328924: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-02-10 11:09:18.683605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-02-10 11:09:18.683731: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0
2021-02-10 11:09:18.683792: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N
2021-02-10 11:09:18.683943: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21808 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3090, pci bus id: 0000:01:00.0, compute capability: 8.6)
2021-02-10 11:09:18.684411: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Model loaded.
3.82177996635437 seconds.
Traceback (most recent call last):
  File "demo.py", line 149, in loadModel
    self.updateCloud()
  File "demo.py", line 202, in updateCloud
    depth = (1000 / self.model.predict( np.expand_dims(self.glWidget.rgb, axis=0)  )) / 1000
  File "C:\Users\Rendering\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1577, in predict
    version_utils.disallow_legacy_graph('Model', 'predict')
  File "C:\Users\Rendering\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow\python\keras\utils\version_utils.py", line 122, in disallow_legacy_graph
    raise ValueError(error_msg)
ValueError: Calling `Model.predict` in graph mode is not supported when the `Model` instance was constructed with eager mode enabled. Please construct your `Model` instance in graph mode or call `Model.predict` with eager mode enabled.

**Comment by jonasjohansson** [comment]
Needed to disable eager mode.

**Comment by ykm886** [comment]
请问你解决这个问题了吗
