### ISSUE TITLE
occurs error when training with nyu

### ISSUE THREAD

**Issue by aaronjie** [ialhashim/DenseDepth#23]
Hi, thanks for your nice paper and code, however, I get an error when training on nyu dataset without any other changes on windows.

---- error logs ----
Epoch 1/20
 191/6336 [..............................] - ETA: 2:07:04 - loss: 0.2413Traceback (most recent call last):
  File "train.py", line 87, in <module>
    model.fit_generator(train_generator, callbacks=callbacks, validation_data=test_generator, epochs=args.epochs, shuffle=True)
  File "C:\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Python\Python36\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Python\Python36\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 601, in get
    six.reraise(*sys.exc_info())
  File "C:\Python\Python36\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 595, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Python\Python36\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
  File "C:\Python\Python36\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "E:\Development\code\DenseDepth\data.py", line 70, in __getitem__
    y = np.clip(np.asarray(Image.open( BytesIO(self.data[sample[1]]) )).reshape(480,640,1)/255*self.maxDepth,0,self.maxDepth)
ValueError: cannot reshape array of size 1 into shape (480,640,1)

----system information----
os: windows 10
tensorflow: 1.13.1
keras: 2.2.4

**Comment by ialhashim** [comment]
This seem to be an issue with corrupted data (array of size 1). Try downloading the data file again and see if you are still facing this problem.

**Comment by LiZhenLiangLee** [comment]
@aaronjie  Do you solve this error now? I have the same error. Can you share your solution?

**Comment by LiZhenLiangLee** [comment]
@aaronjie  Do you solve this error now? I have similar error, and I download the data file again but useless. Can you share your solution？
