### ISSUE TITLE
Dependencies for RGBD Viewer

### ISSUE THREAD

**Issue by MasterSkepticista** [ialhashim/DenseDepth#37]
I get this error while running 

`python demo.py`

```
Traceback (most recent call last):
  File "demo.py", line 414, in <module>
    window = Window()
  File "demo.py", line 80, in __init__
    self.glWidget = GLWidget()
  File "demo.py", line 238, in __init__
    self.updateRGBD()
  File "demo.py", line 367, in updateRGBD
    self.pos = self.pos + glm.vec3(0, -0.06, -0.3)
AttributeError: module 'glm' has no attribute 'vec3'
```
I tried glm versions 0.1.0 and latest one as well.

**Comment by ialhashim** [comment]
It seems related to this [issue](https://github.com/ialhashim/DenseDepth/issues/29).

**Comment by MasterSkepticista** [comment]
I installed PyGLM as well, it still shows the same error. I fear I'm not missing any dependency here.
```Package              Version
-------------------- --------
absl-py              0.7.1
astor                0.8.0
astroid              2.2.5
attrs                19.1.0
backcall             0.1.0
bleach               3.1.0
certifi              2019.3.9
Click                7.0
colorama             0.4.1
cycler               0.10.0
decorator            4.4.0
defusedxml           0.6.0
entrypoints          0.3
gast                 0.2.2
glm                  0.1.0
grpcio               1.21.1
h5py                 2.9.0
imageio              2.5.0
ipykernel            5.1.1
ipython              7.5.0
ipython-genutils     0.2.0
ipywidgets           7.4.2
isort                4.3.20
jedi                 0.13.3
Jinja2               2.10.1
joblib               0.13.2
jsonschema           3.0.1
jupyter              1.0.0
jupyter-client       5.2.4
jupyter-console      6.0.0
jupyter-core         4.4.0
Keras                2.2.4
Keras-Applications   1.0.7
Keras-Preprocessing  1.0.9
kiwisolver           1.1.0
lazy-object-proxy    1.4.1
Markdown             3.1.1
MarkupSafe           1.1.1
matplotlib           3.1.0
mccabe               0.6.1
mistune              0.8.4
mock                 3.0.5
nbconvert            5.5.0
nbformat             4.4.0
networkx             2.3
notebook             5.7.8
numpy                1.16.3
opencv-python        3.4.2.17
pandas               0.24.2
pandocfilters        1.4.2
parso                0.4.0
pickleshare          0.7.5
Pillow               6.0.0
pip                  19.1.1
prometheus-client    0.6.0
prompt-toolkit       2.0.9
protobuf             3.7.1
pydot                1.4.1
PyGLM                1.0.0
Pygments             2.4.2
pylint               2.3.1
PyOpenGL             3.1.0
pyparsing            2.4.0
pyrsistent           0.15.2
PySide2              5.12.3
python-dateutil      2.8.0
pytz                 2019.1
PyWavelets           1.0.3
pywinpty             0.5.5
PyYAML               5.1
pyzmq                18.0.1
qtconsole            4.5.1
scikit-image         0.15.0
scikit-learn         0.21.2
scipy                1.0.0
seaborn              0.9.0
Send2Trash           1.5.0
setuptools           28.8.0
shiboken2            5.12.3
six                  1.12.0
tensorboard          1.12.2
tensorflow-estimator 1.13.0
tensorflow-gpu       1.12.0
termcolor            1.1.0
terminado            0.8.2
testpath             0.4.2
tflearn              0.3.2
tornado              6.0.2
tqdm                 4.32.1
traitlets            4.3.2
typed-ast            1.3.5
wcwidth              0.1.7
webencodings         0.5.1
Werkzeug             0.15.4
wheel                0.33.4
widgetsnbextension   3.4.2
wrapt                1.11.1```

**Comment by ialhashim** [comment]
Could you try uninstalling the `glm` package.

**Comment by MasterSkepticista** [comment]
Worked like a charm. You can close this issue. :)
