### ISSUE TITLE
Not JSON Serializable Error When Saving the Model

### ISSUE THREAD

**Issue by resindraburiza** [ialhashim/DenseDepth#59]
Dear Ibraheem Alhashim,

Thank you for sharing your code. When I tried your code to infer depth using pre-trained model, everything is fine. But then, I tried to train the network using provided code and dataset. I used the same tensorflow and keras version as stated in the Readme (TF 1.13.2 and Keras 2.2.4). So, firstly I tried to run the training on a very small subset of provided dataset but when saving the model, I got this error. Have you ever got this error? Did I use different TF or Keras version than yours? Thank you for your assistance.

Best,
Resindra

`Traceback (most recent call last):
  File "train.py", line 92, in <module>
    basemodel.save(runPath + '/model.h5')
  File "/home/aresindra/.virtualenvs/tensor113/lib/python3.5/site-packages/keras/engine/network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "/home/aresindra/.virtualenvs/tensor113/lib/python3.5/site-packages/keras/engine/saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "/home/aresindra/.virtualenvs/tensor113/lib/python3.5/site-packages/keras/engine/saving.py", line 84, in _serialize_model
    model_config = json.dumps(model_config, default=get_json_type)
  File "/usr/lib/python3.5/json/__init__.py", line 237, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/home/aresindra/.virtualenvs/tensor113/lib/python3.5/site-packages/keras/engine/saving.py", line 74, in get_json_type
    raise TypeError('Not JSON Serializable: %s' % (obj,))
TypeError: Not JSON Serializable: ?`

**Comment by ialhashim** [comment]
https://github.com/ialhashim/DenseDepth/issues/16#issuecomment-486293383

**Comment by resindraburiza** [comment]
Dear Ibraheem Alhashim,

thank you for your guidance and I'm so sorry that this question had been asked before.

**Comment by ialhashim** [comment]
Not a problem, best of luck
