### ISSUE TITLE
about depth_shape size 

### ISSUE THREAD

**Issue by mahxn0** [ialhashim/DenseDepth#60]
thanks for your great work
I can't understand why shape_rgb is 640*480, the shape_depth is 320*240? 

If I used kitti.h5 to fintuning,my dataset is 1280*720, First I resized all rgb and depth to 370*1224?

then there some code do I need to modify ?

there is my dataload code:
```
import numpy as np
from utils import DepthNorm
from io import BytesIO
from PIL import Image
from zipfile import ZipFile
from keras.utils import Sequence
from augment import BasicPolicy

def extract_zip(input_zip):
    input_zip=ZipFile(input_zip)
    return {name: input_zip.read(name) for name in input_zip.namelist()}

def nyu_resize_x(img, resolution=370, padding=6):
    from skimage.transform import resize
    return resize(img, (resolution, 1224), preserve_range=True, mode='reflect', anti_aliasing=True )

def nyu_resize_y(img, resolution=370, padding=6):
    from skimage.transform import resize
    return resize(img, (resolution,612), preserve_range=True, mode='reflect', anti_aliasing=True )

def get_nyu_data(batch_size, nyu_data_zipfile='nyu_data.zip'):
    #data = extract_zip(nyu_data_zipfile)
    #nyu2_train = list((row.split(',') for row in (data['data/nyu2_train.csv']).decode("utf-8").split('\n') if len(row) > 0))
    #nyu2_test = list((row.split(',') for row in (data['data/nyu2_test.csv']).decode("utf-8").split('\n') if len(row) > 0))
    img_lists,label_lists=None,None
    nyu2_train=[]
    nyu2_test=[]
    with open("/media/mahxn0/DATA/rili/train/train.txt","r") as f1:
        img_lists=f1.readlines()
    with open("/media/mahxn0/DATA/rili/train/label.txt","r") as f2:
        label_lists=f2.readlines()
    for i in range(len(img_lists)):
        item = [img_lists[i].rstrip('\n'),label_lists[i].rstrip('\n')]
        nyu2_train.append(item)
    with open("/media/mahxn0/DATA/rili/test/test.txt","r") as f3:
        img_test_lists=f3.readlines()
    with open("/media/mahxn0/DATA/rili/test/test_label.txt","r") as f4:
        label_test_lists=f4.readlines()
    for i in range(len(img_test_lists)):
        item = [img_test_lists[i].rstrip('\n'),label_test_lists[i].rstrip('\n')]
        nyu2_test.append(item)
    shape_rgb = (batch_size, 370, 1224, 3)
    shape_depth = (batch_size, 185, 612, 1)

    # Helpful for testing...
    if False:
        nyu2_train = nyu2_train[:10]
        nyu2_test = nyu2_test[:10]

    return nyu2_train, nyu2_test, shape_rgb, shape_depth

def get_nyu_train_test_data(batch_size):
    nyu2_train, nyu2_test, shape_rgb, shape_depth = get_nyu_data(batch_size)

    train_generator = NYU_BasicAugmentRGBSequence(nyu2_train, batch_size=batch_size, shape_rgb=shape_rgb, shape_depth=shape_depth)
    test_generator = NYU_BasicRGBSequence(nyu2_test, batch_size=batch_size, shape_rgb=shape_rgb, shape_depth=shape_depth)

    return train_generator, test_generator

class NYU_BasicAugmentRGBSequence(Sequence):
    def __init__(self,dataset, batch_size, shape_rgb, shape_depth, is_flip=False, is_addnoise=False, is_erase=False):
        self.dataset = dataset
        self.policy = BasicPolicy( color_change_ratio=0.50, mirror_ratio=0.50, flip_ratio=0.0 if not is_flip else 0.2, 
                                    add_noise_peak=0 if not is_addnoise else 20, erase_ratio=-1.0 if not is_erase else 0.5)
        self.batch_size = batch_size
        self.shape_rgb = shape_rgb
        self.shape_depth = shape_depth
        self.maxDepth = 1000.0

        from sklearn.utils import shuffle
        self.dataset = shuffle(self.dataset, random_state=0)

        self.N = len(self.dataset)

    def __len__(self):
        return int(np.ceil(self.N / float(self.batch_size)))

    def __getitem__(self, idx, is_apply_policy=True):
        batch_x, batch_y = np.zeros( self.shape_rgb ), np.zeros( self.shape_depth )
        # Augmentation of RGB images
        for i in range(batch_x.shape[0]):
            index = min((idx * self.batch_size) + i, self.N-1)

            sample = self.dataset[index]

            x = np.clip(np.asarray(Image.open( sample[0] )).reshape(370, 1224,3)/255,0,1)
            y = np.clip(np.asarray(Image.open( sample[1] )).reshape(370, 1224,1)/255*self.maxDepth,0,self.maxDepth)
            y = DepthNorm(y, maxDepth=self.maxDepth)
            batch_x[i] = nyu_resize_x(x, 370)
            batch_y[i] = nyu_resize_y(y, 185)

            if is_apply_policy: batch_x[i], batch_y[i] = self.policy(batch_x[i], batch_y[i])

            # DEBUG:
            #self.policy.debug_img(batch_x[i], np.clip(DepthNorm(batch_y[i])/maxDepth,0,1), idx, i)
        #exit()

        return batch_x, batch_y

class NYU_BasicRGBSequence(Sequence):
    def __init__(self,dataset, batch_size,shape_rgb, shape_depth):
        self.dataset = dataset
        self.batch_size = batch_size
        self.N = len(self.dataset)
        self.shape_rgb = shape_rgb
        self.shape_depth = shape_depth
        self.maxDepth = 1000.0

    def __len__(self):
        return int(np.ceil(self.N / float(self.batch_size)))

    def __getitem__(self, idx):
        batch_x, batch_y = np.zeros( self.shape_rgb ), np.zeros( self.shape_depth )
        for i in range(self.batch_size):            
            index = min((idx * self.batch_size) + i, self.N-1)

            sample = self.dataset[index]

            x = np.clip(np.asarray(Image.open( sample[0])).reshape(370,1224,3)/255,0,1)
            y = np.asarray(Image.open(sample[1]), dtype=np.float32).reshape(185,612,1).copy().astype(float) / 10.0
            y = DepthNorm(y, maxDepth=self.maxDepth)

            batch_x[i] = nyu_resize(x, 370)
            batch_y[i] = nyu_resize(y, 185)

            # DEBUG:
            #self.policy.debug_img(batch_x[i], np.clip(DepthNorm(batch_y[i])/maxDepth,0,1), idx, i)
        #exit()

        return batch_x, batch_y
```
look forward you reply ^_^

**Comment by ialhashim** [comment]
The output of the depth can be interpolated to the full size. Generally the memory limit decides how large the dense estimation would be.. in this case its half the input.

For the KITTI model you are on the right track I think. Let me know if you encounter errors.

**Comment by mahxn0** [comment]
@ialhashim 
Thank you, I'm Sad .
```
Epoch 1/20
/home/mahxn0/M_DeepLearning/RGBD/DenseDepth/utils.py:5: RuntimeWarning: divide by zero encountered in true_divide
  return maxDepth / x
Traceback (most recent call last):
  File "train.py", line 87, in <module>
    model.fit_generator(train_generator, callbacks=callbacks, validation_data=test_generator, epochs=args.epochs, shuffle=True)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/keras/engine/training_generator.py", line 217, in fit_generator
    class_weight=class_weight)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/keras/engine/training.py", line 1217, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1382, in __call__
    run_metadata_ptr)
  File "/home/mahxn0/anaconda3/envs/python3_tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 519, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [2,1664,22,76] vs. shape[1] = [2,256,23,76]
	 [[Node: up1_concat/concat = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _class=["loc:@training/Adam/gradients/AddN_396"], _device="/job:localhost/replica:0/task:0/device:GPU:0"](up1_concat/concat-0-TransposeNHWCToNCHW-LayoutOptimizer, pool3_pool/AvgPool, training/Adam/gradients/loss/conv3_loss/Mean_6_grad/Maximum)]]
	 [[Node: loss/conv3_loss/ShapeN_1/_10077 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_27042_loss/conv3_loss/ShapeN_1", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
```
look forward you reply  again !^_^!

**Comment by valentinoPereira** [comment]
Hey what about training my own dataset of 1920x1080 images? Do I need to resize them? Where in the code do I need to make changes? Please help since I'm stuck on this for days.
![image](https://user-images.githubusercontent.com/21219324/66758282-9b1a5500-eebb-11e9-848b-9da5c97440a0.png)

This training bug does not seem to go away.. Also when I do some changes, the training exits on first epoch

**Comment by ialhashim** [comment]
You have different options to fix this. Either you simply resize all inputs to  (384, 1248, 3) (height, width, channel) and do refinements on the trained model or you could try to compute the best values from the original data that can be divided by 32 (I think in this case just cropping the height to 1056).

Which approach is best depends on many things and its hard to predict before hand. One thing to keep in mind is the batch size. If your card doesn't allow for more than 4 because of this larger image think about resizing until it fit. I found that batch size of 8 usually give out the best result.

**Comment by valentinoPereira** [comment]
So I leave the width as it is and only resize the height to 1056.. so will my final training image be 1920x1056? And set the depth shape to half this value right?

**Comment by ialhashim** [comment]
Exactly.

**Comment by valentinoPereira** [comment]
Hi, I've done as you said but the training wouldn't start. I have put a print statement in the `on_epoch_end` callback function but the training isn't reaching there. Following is my log:
![image](https://user-images.githubusercontent.com/21219324/66821740-9360bc00-ef60-11e9-9311-c413c9f9be9d.png)
