### ISSUE TITLE
saving.py type error 

### ISSUE THREAD

**Issue by MMehdiMousavi** [ialhashim/DenseDepth#64]
Hey, 
Im trying to recreate the training process on your code, it trains fine, but when saving i get this error: 

> 1/1 [==============================] - 68s 68s/step - loss: 0.8579 - val_loss: 0.7944
Traceback (most recent call last):
  File "D:/DenseDepth-master/train.py", line 94, in <module>
    basemodel.save('bokhoresh.h5')
  File "C:\Anaconda\envs\py3\lib\site-packages\keras\engine\network.py", line 1090, in save
    save_model(self, filepath, overwrite, include_optimizer)
  File "C:\Anaconda\envs\py3\lib\site-packages\keras\engine\saving.py", line 382, in save_model
    _serialize_model(model, f, include_optimizer)
  File "C:\Anaconda\envs\py3\lib\site-packages\keras\engine\saving.py", line 84, in _serialize_model
    model_config = json.dumps(model_config, default=get_json_type)
  File "C:\Anaconda\envs\py3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Anaconda\envs\py3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Anaconda\envs\py3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Anaconda\envs\py3\lib\site-packages\keras\engine\saving.py", line 74, in get_json_type
    raise TypeError('Not JSON Serializable: %s' % (obj,))
TypeError: Not JSON Serializable: ?

can you please check this out?

**Comment by MMehdiMousavi** [comment]
Okay, so i looked at closed issues and saw a fix 

from tensorflow.python.framework.tensor_shape import Dimension
if type(obj) == Dimension:
  return int(obj.value or 0)

I added this code to saving.py in keras engine, 
now it saves the model just fine, BUT  when i load it again to test it, i get this error: 

  File "D:/DenseDepth-master/test.py", line 30, in <module>
    inputs = load_images( glob.glob(args.input) )
  File "D:\DenseDepth-master\utils.py", line 33, in load_images
    return np.stack(loaded_images, axis=0)
  File "C:\Anaconda\envs\py3\lib\site-packages\numpy\core\shape_base.py", line 412, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

**Comment by ialhashim** [comment]
This error seem to be related to missing image files.
